# Generated by Django 4.0.4 on 2022-06-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
