# Generated by Django 4.0.4 on 2022-05-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
