# Generated by Django 4.0.4 on 2022-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_response', '0002_alter_workerresponse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerresponse',
            name='date',
            field=models.DateField(),
        ),
    ]
