# Generated by Django 4.0.4 on 2022-05-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_response', '0003_alter_workerresponse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerresponse',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('H', 'On Hold'), ('C', 'Complete')], default='I', max_length=15),
        ),
    ]
