# Generated by Django 4.0.4 on 2022-05-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_response', '0004_workerresponse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerresponse',
            name='status',
        ),
    ]
