# Generated by Django 4.0.4 on 2022-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('unit', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=255)),
                ('entry', models.CharField(choices=[('Enter', 'Enter Anytime'), ('Call', 'Call Before Entry')], default='Enter', max_length=30)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('None', 'No Priority')], default='None', max_length=15)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('H', 'On Hold'), ('C', 'Complete')], default='I', max_length=15)),
            ],
        ),
    ]
