# Generated by Django 4.0.4 on 2022-05-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorders',
            name='status',
        ),
    ]
