# Generated by Django 4.0.4 on 2022-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_remove_workorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorders',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('H', 'On Hold'), ('C', 'Complete')], default='I', max_length=15),
        ),
    ]
