# Generated by Django 4.0.4 on 2022-05-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
