# Generated by Django 4.0.4 on 2022-05-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('comments', models.CharField(max_length=255)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.workorders')),
            ],
        ),
    ]
